### ISSUE TITLE
Unsure how to configure Android

### ISSUE THREAD

**Issue by tupakapoor** [ingageco/capacitor-read-native-setting#1]
Hello, my MainActivity.java is an empty class so I'm not sure where to put the bit that is mentioned in the README as needing to go inside bridge activity:
```
// add class inside bridge activity:
add(CapacitorReadNativeSetting.class);
```

My MainActivity.java looks like this:

```
import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {}
```

Can you explain where I need to add the call to `add(CapacitorReadNativeSetting.class)` please? Thanks!

**Comment by ingageco** [comment]
@tupakapoor Unless you are still on Capacitor 2, this repo is currently outdated. I will be adding support for Capacitor 3+ soon. 

Your question has to do with something that was required in v2 but is not in v3 and beyond, which is why i say that.

**Comment by tupakapoor** [comment]
Ok understood - thank you!
